# Generated by Django 3.2.15 on 2023-03-22 17:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', ckeditor.fields.RichTextField()),
                ('blog_title', models.CharField(max_length=33)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('blog_image', models.ImageField(blank=True, default='ppp.jpg', null=True, upload_to='')),
                ('Pen_name', models.CharField(max_length=7)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogging.tags')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['upload'],
            },
        ),
    ]
